[package]
name = "egor00f/inputlib"

description = "Just small library for more easy working with user input"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/Ukuroks-Games/InputLib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["*"]

include = ["src", "src/**", "wally.toml", "README.md", "init.lua"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]
